Refactor of the coercion and validation logic
nicolasblanco/rails_param pull request #62
Opened 2021-04-17 19:00 UTC by ifellinaholeonce

## Description
Hey there 👋 !
First off, thanks a lot for this gem!

I've written a refactor of the code here in the hopes of making it a little easier to maintain. I know this is _a lot_ of changes coming all at once. I'm wondering if this is something you'd be interested in? Happy to make changes and address any concerns you might have.

Thanks a lot for your time. Looking forward to hearing from you and getting these changes to a place that you'd be interested in merging them in.

**Highlights**
- I've made it a top priority to not change any of the existing specs, to ensure behaviour doesn't change.
- I've added unit specs for the classes I've added to maintain high code coverage.
- `Parameter` class was introduced to represent the current param being processed. It takes in `name`, `value`, `type` and `options`. It knows how to check for defaults, transform and call a new `Validator` on itself.
- `Validator` class acts as a factory for creating subclasses with validation logic. 
- `Coercion` class also acts as a factory for coercing values based on the provided type. The logic for the different types of coercion live in subclasses, ie. `Coercion::ArrayParam`.

## Todos

## Additional Notes
Special thanks to @ClaytonPassmore for the help

2021-04-18 06:44 UTC, iMacTia commented
Thank you @ifellinaholeonce, this work is impressive! And very much welcome 👏! I want to take the proper time to review this and decide what to do as I think it may deserve a major version shipping.

May I ask what triggered you on doing this refactoring 😮?

2021-04-19 00:18 UTC, ifellinaholeonce commented
That's really exciting to hear @iMacTia. Looking forward to hearing your thoughts on it.

Honestly, the refactor started by digging into what I thought was a bug at the time and then it continued on as an opportunity to learn and practice some skills. I had a great time doing it.

2021-04-19 09:13 UTC, iMacTia requested changes
@ifellinaholeonce thanks again for the massive contribution 👏!
Overall I'm impressed with the refactoring you've been doing on the gem and I very much like the result!

After careful consideration, I'd be inclined to make this a v1.0 release.
That means we'd not be restricted in keeping the gem fully backwards-compatible, although we want to minimise disruptions in order to make life easier for those upgrading 😄
We'd also need to list all breaking changes into a new `UPGRADING.md` document we can add to the root of the repo. I'd suggest to add it in this PR and fill it while implementing the braking changes.

If you also like that idea, I've left a few comments that I understand were not an option before this decision, and I hope you'll have the time and will to make these changes.
If that's not the case, then I completely understand that. You've already spent extensive time on this PR, so I'll be happy to take over for you if you prefer to focus your attention elsewhere.

2021-04-19 09:13 UTC, iMacTia commented on spec/spec_helper.rb
> +require 'rails_param/validator'
These files should automatically be required by `rails_param`.
Otherwise, users of the gem will need to manually require them as well

2021-04-19 22:50 UTC, ifellinaholeonce commented
That's really exciting to hear! 😃  Thanks @iMacTia. 

I'm happy to carry on with this. I'll address your comments on this PR. Likely in the next day or two.

2021-04-24 23:58 UTC, ifellinaholeonce commented on lib/rails_param/param.rb
>    module Param
Hey, just pushed this commit and want to confirm this is what you were meaning by removing that module:

https://github.com/nicolasblanco/rails_param/pull/62/commits/30b153999ed310c744c7e59e6a5cc7f136e271c5#diff-49928da1909fa8d3e936d912a4938cd3ab685b3b490e2220deb47a9b93032e21R1

2021-04-25 08:09 UTC, iMacTia commented on lib/rails_param/param.rb
>    module Param
@ifellinaholeonce yes, that looks great 👏 !

2021-04-30 03:06 UTC, ifellinaholeonce commented
Hey @iMacTia 

Just following up here. It took me a little longer than expected, it was a bit of a tough nut to crack but I managed to address your thoughts on the `MockController` class. Ultimately, I moved all the logic from the base `param!` method into a new class `ParamEvaluator` which allowed me to remove the `MockController` class.

This is the commit where that is introduced: https://github.com/nicolasblanco/rails_param/pull/62/commits/44d875c844fbc473bfc8962148ba689cad1617c8

I haven't added a `UPGRADING.md` since all of these changes so far have been backward compatible.

Looking forward to your thoughts on this approach and where we can go from here.

2021-04-30 08:45 UTC, iMacTia commented
Thank you so much @ifellinaholeonce!
I can't wait to review this, will try to do it as soon as possible.
Thanks again for all the hard work 🙏🎉!

2021-04-30 10:28 UTC, iMacTia approved these changes
This looks great and the important comments were all addressed.
Assuming tests will be green, I feel like we can get this merged, and then it will be just a bit of polishing before we release v1.0 👍

2021-04-30 10:28 UTC, iMacTia commented on lib/rails_param/param_evaluator.rb
> +      end
I still feel like this bit should be delegated to the Array and Hash validators, but this can be done on a follow-up PR 👍

2021-04-30 11:50 UTC, iMacTia commented
Tests green, I'm merging this in 🎉 !
Thanks again @ifellinaholeonce, this is definitely a monumental piece of work and I really appreciate you taking the time to help us out.

Actually I was wondering if you'd be considering becoming a maintainer of this gem?
Think about it and let me know, we could then ask @nicolasblanco if he agrees as ultimately he'll need to make you one 😄

2021-04-30 11:50 UTC, merged

2021-05-05 14:00 UTC, ifellinaholeonce commented
Hey @iMacTia I'm interested in learning a bit more about becoming a maintainer for the gem😄 

Would you be open to a bit of back and forth about it? Happy to do email, or open an issue in this repo or anything really if you have a preference.

2021-05-10 02:10 UTC, ifellinaholeonce commented
haha yes I struggled with that same problem. You can find me on Gitter in the `rails` community 😄